;;; Stable byte encodings owned by gerbil-poo.

(export #t)

(import
  (only-in :std/assert assert!)
  (only-in :std/vector/u8vector
           big sint->u8vector u8vector->sint uint->u8vector u8vector->uint)
  (only-in :std/number/misc sint-length-in-u8 uint-length-in-u8))

(def (write-u8vector* bytes port)
  (if (zero? (u8vector-length bytes)) 0 (write-u8vector bytes port)))
(def (read-u8vector* bytes port)
  (if (zero? (u8vector-length bytes)) 0 (read-u8vector bytes port)))
(def (unmarshal-n-u8 size port)
  (if (zero? size) #u8()
      (let ((bytes (make-u8vector size)))
        (assert! (= size (read-u8vector* bytes port)))
        bytes)))
(def (unmarshal-uint16 port)
  (def high (read-u8 port))
  (def low (read-u8 port))
  (fx+ low (fxarithmetic-shift high 8)))
(def (unmarshal-sized16-u8vector port)
  (unmarshal-n-u8 (unmarshal-uint16 port) port))
(def (marshal-uint16 n port)
  (assert! (<= 0 n 65535))
  (write-u8vector* (uint->u8vector n big 2) port))
(def (marshal-sized16-u8vector bytes port)
  (marshal-uint16 (u8vector-length bytes) port)
  (write-u8vector* bytes port))
(def (u8vector<-<-marshal marshal)
  (lambda (x) (call-with-output-u8vector (lambda (port) (marshal x port)))))
(def (<-u8vector<-unmarshal unmarshal)
  (lambda (bytes)
    (call-with-input-u8vector bytes
      (lambda (port)
        (def value (unmarshal port))
        (assert! (not (eof-object? value)))
        (assert! (eof-object? (read-u8 port)))
        value))))
(def (marshal<-u8vector<- bytes<-)
  (lambda (x port) (write-u8vector* (bytes<- x) port)))
(def (unmarshal<-<-u8vector <-bytes n)
  (lambda (port) (<-bytes (unmarshal-n-u8 n port))))
(def (read-uint-u8vector length port)
  (u8vector->uint (unmarshal-n-u8 length port)))
(def (write-uint-u8vector n length port)
  (write-u8vector* (uint->u8vector n big length) port))
(def (read-sint-u8vector length port)
  (u8vector->sint (unmarshal-n-u8 length port) big length))
(def (write-sint-u8vector n length port)
  (write-u8vector* (sint->u8vector n big length) port))

(def (read-varint port)
  (let ((x (read-u8 port)))
    (if (< x 128)
      (cond
       ((< x 64) x)
       ((< x 127)
        (def length (- x 63))
        (def n (read-uint-u8vector length port))
        (assert! (and (>= n 64) (= (uint-length-in-u8 n) length))) n)
       (else
        (def length (read-varint port))
        (def n (read-uint-u8vector length port))
        (assert! (and (>= length 64) (= (uint-length-in-u8 n) length))) n))
      (cond
       ((>= x 192) (- x 256))
       ((> x 128)
        (def length (- 192 x))
        (def n (read-sint-u8vector length port))
        (assert! (and (< n -64) (= length (sint-length-in-u8 n)))) n)
       (else
        (def length (- (read-varint port)))
        (def n (read-sint-u8vector length port))
        (assert! (and (> length 63) (= length (sint-length-in-u8 n)))) n)))))
(def (write-varint n port)
  (if (negative? n)
    (if (>= n -64) (write-u8 (bitwise-and n 255) port)
        (let ((length (sint-length-in-u8 n)))
          (if (<= length 63)
            (begin (write-u8 (- 192 length) port)
                   (write-sint-u8vector n length port))
            (begin (write-u8 128 port) (write-varint (- length) port)
                   (write-sint-u8vector n length port)))))
    (if (<= n 63) (write-u8 n port)
        (let ((length (uint-length-in-u8 n)))
          (if (<= length 63)
            (begin (write-u8 (+ length 63) port)
                   (write-uint-u8vector n length port))
            (begin (write-u8 127 port) (write-varint length port)
                   (write-uint-u8vector n length port)))))))
(def (read-varuint port)
  (def x (read-u8 port))
  (cond
   ((< x 128) x)
   ((< x 255)
    (def length (- x 127))
    (def n (read-uint-u8vector length port))
    (assert! (and (> n 127) (= (uint-length-in-u8 n) length))) n)
   (else
    (def length (read-varuint port))
    (def n (read-uint-u8vector length port))
    (assert! (and (> length 127) (= (uint-length-in-u8 n) length))) n)))
(def (write-varuint n port)
  (if (<= n 127) (write-u8 n port)
      (let ((length (uint-length-in-u8 n)))
        (if (<= length 127)
          (begin (write-u8 (+ length 127) port)
                 (write-uint-u8vector n length port))
          (begin (write-u8 255 port) (write-varuint length port)
                 (write-uint-u8vector n length port))))))
