(export (for-syntax call<-formals))

(begin-syntax
  (def (parse-formal formal)
    (syntax-case formal ()
      (_ (identifier? formal) [formal #f #f #f #f])
      ((name default) (identifier? #'name) [#'name #f #t #'default #f])
      (_ (error "Invalid formal parameter" formal))))
  (def (parse-formals formals)
    (let loop ((result []) (formals formals))
      (syntax-case formals ()
        (rest (identifier? #'rest) (reverse (cons [#'rest #f #t '() #t] result)))
        (() (reverse result))
        ((keyword value . more) (stx-keyword? #'keyword)
         (match (parse-formal #'value)
           ([name _ optional? default _]
            (loop (cons [name #'keyword optional? default #f] result) #'more))))
        ((value . more) (loop (cons (parse-formal #'value) result) #'more))
        (_ (error "Invalid formals" formals)))))
  (def (call<-parsed-formal parsed)
    (match parsed ([name keyword _ _ _] (if keyword [keyword name] [name]))))
  (def (call<-formals prefix formals)
    (def parsed (parse-formals formals))
    (def rest? (and (pair? parsed) (fifth (last parsed))))
    (with-syntax ((((call ...) ...) (map call<-parsed-formal parsed))
                  ((prefix ...) prefix)
                  ((apply* ...) (if rest? #'(apply) [])))
      #'(apply* ... prefix ... call ... ...))))
